### ISSUE TITLE
[EPIC] Migrate Infrastructure to Apache Software Foundation

### ISSUE THREAD

**Issue by jonnybot0** [apache/groovy-geb#214]
This is an epic to track all the work going on to move Geb under the Apache Software Foundation.

- [ ] Migrate CI to Jenkins - https://github.com/apache/groovy-geb/issues/213
- [ ] Move Geb to a static ASF-hosted Webiste - https://github.com/apache/groovy-geb/issues/208
- [ ] Update site to note Geb is an ASF subproject of Groovy https://github.com/apache/groovy-geb/issues/207
- [ ] Move maven coordinates to be under org.apache.groovy.geb rather than org.gebish
